spring.application.name: DemoApp
spring:
  jpa:
    hibernate:
      ddl-auto: validate

exchanges.apis:
  configs:
    - url: https://api.frankfurter.dev/v1/latest
      service-id: frankfurtApi
    - url: https://v6.exchangerate-api.com/v6/5781c7d319af7a3117f90e80
      service-id: exchangerateApi
